ydan_dbt:
  outputs:
    dev:
      account: twjvfvg-mp11590
      database: YDAN
      password: Ydanproject123
      role: developers
      schema: SILVER_LAYER
      threads: 4
      type: snowflake
      user: vinicio_yusuke
      warehouse: COMPUTE_WH
  target: dev