{{ config(materialized='table') }}

WITH

CAPTIONS AS (
  SELECT *
  FROM BRONZE_LAYER.CAPTIONS
),

VIDEOS AS (
  SELECT *
  FROM {{ ref('videos') }}
)


SELECT
  CAPTION_VIDEO_ID,
  VIDEOS.VIDEO_CHANNEL_ID AS CAPTION_CHANNEL_ID,
  VIDEOS.VIDEO_UPLOAD_DATE AS CAPTION_VIDEO_UPLOAD_DATE,
  VIDEOS.VIDEO_VIEWS_NUM AS CAPTION_VIDEO_VIEWS_NUM,
  UPPER(CAPTION_WORD.VALUE) AS CAPTION_WORD_TEXT,
  CAPTION_LINE_START_SECONDS_FLOAT AS CAPTION_SECONDS_FLOAT

FROM CAPTIONS

JOIN VIDEOS
  ON CAPTIONS.CAPTION_VIDEO_ID = VIDEOS.VIDEO_ID

JOIN LATERAL 
  SPLIT_TO_TABLE(CAPTION_LINE_TEXT, ' ') CAPTION_WORD

WHERE
  CAPTION_WORD.VALUE <> '' AND
  CAPTION_VIDEO_ID IS NOT NULL AND
  CAPTION_LINE_START_SECONDS_FLOAT >= 0