{{ config(materialized='table') }}

WITH

CHANNELS AS (
  SELECT *
  FROM ref('channels')
),

VIDEO_CHANNELS AS (
  SELECT *
  FROM ref('video_channels')
)

SELECT
  VIDEO_CHANNELS.CHANNEL_ID,
  VIDEO_CHANNELS.CHANNEL_SUBSCRIBERS_NUM,
  VIDEO_CHANNELS.CHANNEL_VIDEO_COUNT_NUM,
  VIDEO_CHANNELS.CHANNEL_SCRAPE_TIMESTAMP,
  CHANNELS.CHANNEL_ID IS NOT NULL AS CHANNEL_WAS_SCRAPED_BOOL

FROM VIDEO_CHANNELS

LEFT JOIN CHANNELS
  ON VIDEO_CHANNELS.CHANNEL_ID = CHANNELS.CHANNEL_ID
