{{ config(materialized='table') }}

WITH

CHANNELS AS (
  SELECT *
  FROM BRONZE_LAYER.CHANNELS
)


SELECT
  CHANNEL_ID,
  CHANNEL_SUBSCRIBERS_NUM,
  CHANEL_VIDEO_COUNT_NUM AS CHANNEL_VIDEO_COUNT_NUM,
  CHANNEL_SCRAPE_TIMESTAMP

FROM CHANNELS

WHERE
  CHANNEL_ID IS NOT NULL AND
  CHANNEL_SUBSCRIBERS_NUM >= 1000000 AND
  CHANEL_VIDEO_COUNT_NUM >= 0 AND
  CHANNEL_SCRAPE_TIMESTAMP >= '2025-04-30' AND
  CHANNEL_SCRAPE_TIMESTAMP < '2025-05-05'