{{ config(materialized='table') }}

WITH

HEATMAP AS (
  SELECT *
  FROM BRONZE_LAYER.HEATMAP
),

VALID_HEATMAPS AS (
  SELECT HEATMAP_VIDEO_ID
  FROM HEATMAP
  WHERE HEATMAP_POSITION_SERIAL_NUM = 99
  GROUP BY HEATMAP_VIDEO_ID
),

VIDEOS AS (
  SELECT *
  FROM {{ ref('videos') }}
)


SELECT 
  HEATMAP.HEATMAP_VIDEO_ID,
  VIDEOS.VIDEO_DURATION_SECONDS_FLOAT / 100 * HEATMAP.HEATMAP_POSITION_SERIAL_NUM AS HEATMAP_START_SECONDS_FLOAT,
  VIDEOS.VIDEO_DURATION_SECONDS_FLOAT / 100 * (HEATMAP.HEATMAP_POSITION_SERIAL_NUM+1) AS HEATMAP_END_SECONDS_FLOAT,
  HEATMAP.HEATMAP_VALUE_FLOAT

FROM HEATMAP

JOIN VIDEOS
  ON HEATMAP.HEATMAP_VIDEO_ID = VIDEOS.VIDEO_ID

JOIN VALID_HEATMAPS
  ON HEATMAP.HEATMAP_VIDEO_ID = VALID_HEATMAPS.HEATMAP_VIDEO_ID

WHERE
  HEATMAP.HEATMAP_VIDEO_ID IS NOT NULL AND
  HEATMAP.HEATMAP_POSITION_SERIAL_NUM >= 0 AND
  HEATMAP.HEATMAP_POSITION_SERIAL_NUM < 100 AND
  HEATMAP.HEATMAP_VALUE_FLOAT >= 0 AND
  HEATMAP.HEATMAP_VALUE_FLOAT <= 1.0