{{ config(materialized='table') }}

WITH

RECOMMENDATIONS AS (
  SELECT *
  FROM BRONZE_LAYER.RECOMMENDATIONS
),

VIDEOS AS (
  SELECT *
  FROM {{ ref('videos') }}  
)


SELECT
  VIDEO_FROM.VIDEO_ID AS RECOMMENDATION_ORIGIN_VIDEO_ID,
  VIDEO_TO.VIDEO_ID AS RECOMMENDATION_DESTINATION_VIDEO_ID,

  VIDEO_FROM.VIDEO_CHANNEL_ID AS RECOMMENDATION_ORIGIN_CHANNEL_ID,
  VIDEO_TO.VIDEO_CHANNEL_ID AS RECOMMENDATION_DESTINATION_CHANNEL_ID,

  VIDEO_FROM.VIDEO_SCRAPE_TIMESTAMP AS RECOMMENDATION_SCRAPE_TIMESTAMP,

  RECOMMENDATION_POSITION_SERIAL_NUM,

  VIDEO_FROM.VIDEO_VIEWS_NUM AS RECOMMENDATION_ORIGIN_VIDEO_VIEWS_NUM

FROM RECOMMENDATIONS

JOIN VIDEOS VIDEO_FROM
  ON RECOMMENDATIONS.RECOMMENDATION_ORIGIN_VIDEO_ID = VIDEO_FROM.VIDEO_ID

JOIN VIDEOS VIDEO_TO
  ON RECOMMENDATIONS.RECOMMENDATION_DESTINATION_VIDEO_ID = VIDEO_TO.VIDEO_ID

WHERE
  RECOMMENDATION_POSITION_SERIAL_NUM > 0 AND
  RECOMMENDATION_POSITION_SERIAL_NUM <= 20
