{{ config(materialized='table') }}

WITH

VIDEOS AS (
  SELECT *
  FROM {{ ref('videos') }}
)


SELECT
  VIDEO_CHANNEL_ID AS CHANNEL_ID,
  MAX(VIDEO_CHANNEL_SUBSCRIBERS) AS CHANNEL_SUBSCRIBERS_NUM,
  COUNT(VIDEO_ID) AS CHANNEL_VIDEO_COUNT_NUM,
  MAX(VIDEO_SCRAPE_TIMESTAMP) AS CHANNEL_SCRAPE_TIMESTAMP

FROM VIDEOS

GROUP BY
  VIDEO_CHANNEL_ID