{{ config(materialized='table') }}

WITH 

VIDEOS AS (
  SELECT *
  FROM {{ ref('videos') }}
),

KEYWORDS AS (
  SELECT
    KEYWORD_VIDEO_ID,
    KEYWORD_POSITION_SERIAL_NUM,
    KEYWORD_TEXT AS KEYWORD_TEXT
  FROM BRONZE_LAYER.KEYWORDS
)

SELECT
    k.KEYWORD_VIDEO_ID,
    k.KEYWORD_POSITION_SERIAL_NUM,
    UPPER(k.KEYWORD_TEXT) AS KEYWORD_TEXT,
    v.VIDEO_CHANNEL_ID AS KEYWORD_CHANNEL_ID,
    v.VIDEO_VIEWS_NUM AS KEYWORD_VIDEO_VIEWS_NUM,
    v.VIDEO_LIKES_NUM AS KEYWORD_VIDEO_LIKES_NUM,
    TO_DATE(v.VIDEO_UPLOAD_DATE) AS KEYWORD_VIDEO_UPLOAD_DATE
FROM KEYWORDS k
INNER JOIN VIDEOS v
  ON v.VIDEO_ID = k.KEYWORD_VIDEO_ID

WHERE 
    k.KEYWORD_POSITION_SERIAL_NUM >= 0 AND 
    k.KEYWORD_POSITION_SERIAL_NUM < 40 AND
    k.KEYWORD_TEXT RLIKE '^[\\x00-\\x7F]+$' --select only ASCII character, I made this line to avoid keywords in another languages like Japanese, Korean or Arabic
