{{ config(materialized='table') }}

WITH 

VIDEOS AS (
  SELECT *
  FROM BRONZE_LAYER.VIDEOS
  WHERE VIDEO_ID IN ('yfQAnBol6Jw', '8H34jcpEsFs')
)


SELECT
  VIDEO_ID,
  VIDEO_VIEWS_NUM,
  VIDEO_LIKES_NUM,
  VIDEO_IS_LIVE_BOOL,
  VIDEO_IS_FAMILY_FRIENDLY_BOOL,
  VIDEO_SCRAPE_TIMESTAMP,
  VIDEO_DURATION_SECONDS_FLOAT,
  VIDEO_UPLOAD_DATE,
  VIDEO_CHANNEL_SUBSCRIBERS,
  VIDEO_CHANNEL_ID

FROM VIDEOS

WHERE
  VIDEO_ID IS NOT NULL AND
  VIDEO_VIEWS_NUM > 0 AND
  VIDEO_LIKES_NUM >= 0 AND
  VIDEO_IS_LIVE_BOOL IS NOT NULL AND
  VIDEO_IS_FAMILY_FRIENDLY_BOOL IS NOT NULL AND
  VIDEO_SCRAPE_TIMESTAMP >= '2025-04-30' AND
  VIDEO_SCRAPE_TIMESTAMP < '2025-05-12' AND
  VIDEO_DURATION_SECONDS_FLOAT > 0 AND
  VIDEO_CAPTION_LANGUAGE = 'en' AND
  VIDEO_UPLOAD_DATE > '2008' AND
  VIDEO_CHANNEL_SUBSCRIBERS > 0 AND
  VIDEO_CHANNEL_ID IS NOT NULL