services:
  minio:
    image: quay.io/minio/minio
    restart: always
    volumes:
      - ./minio_data:/data:rw
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio-ydan-insecure
      MINIO_ROOT_PASSWORD: minio-ydan-insecure
    command: server /data --console-address ":9001"
    deploy:
      resources:
        limits:
          cpus: 2.0
          memory: 2g
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./postgres_init:/docker-entrypoint-initdb.d:ro
      - ./postgres_data:/var/lib/postgresql/data:rw
    expose:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 6
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "ydan"
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 1g
  scraper:
    build: ./scraper
    restart: always
    depends_on:
      - postgres
      - minio
    environment:
      MINIO_ROOT_USER: minio-ydan-insecure
      MINIO_ROOT_PASSWORD: minio-ydan-insecure
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "ydan"
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 1g
