{{ config(materialized='table') }}

WITH

RECOMMENDATIONS AS (
  SELECT *
  FROM {{ ref('recommendations') }}
),

VIDEOS AS (
  SELECT *
  FROM {{ ref('dim_video') }}  
),

CHANNELS AS (
  SELECT *
  FROM {{ ref('dim_channel') }}
),

DATE_TABLE AS (
  SELECT *
  FROM {{ ref('dim_date') }}
)

SELECT
  VIDEO_FROM.ID_VIDEO AS id_video_origin,
  VIDEO_TO.ID_VIDEO AS id_video_destination,
  CHANNEL_FROM.ID_CHANNEL AS id_channel_origin,
  CHANNEL_TO.ID_CHANNEL AS id_channel_destination,
  DATE_FROM.ID_DATE AS id_video_origin_upload_date,
  DATE_TO.ID_DATE AS id_video_destination_upload_date,
  1 AS count,
  RECOMMENDATIONS.RECOMMENDATION_POSITION_SERIAL_NUM AS position,
  VIDEO_FROM.NUM_VIEWS_VIDEO * (21 - RECOMMENDATIONS.RECOMMENDATION_POSITION_SERIAL_NUM) / 20 AS relevance

FROM RECOMMENDATIONS

JOIN VIDEOS VIDEO_FROM
  ON RECOMMENDATIONS.RECOMMENDATION_ORIGIN_VIDEO_ID = VIDEO_FROM.YOUTUBE_ID_VIDEO

JOIN VIDEOS VIDEO_TO
  ON RECOMMENDATIONS.RECOMMENDATION_DESTINATION_VIDEO_ID = VIDEO_TO.YOUTUBE_ID_VIDEO

JOIN CHANNELS CHANNEL_FROM
  ON RECOMMENDATIONS.RECOMMENDATION_ORIGIN_CHANNEL_ID = CHANNEL_FROM.YOUTUBE_ID_CHANNEL

JOIN CHANNELS CHANNEL_TO
  ON RECOMMENDATIONS.RECOMMENDATION_DESTINATION_CHANNEL_ID = CHANNEL_TO.YOUTUBE_ID_CHANNEL

JOIN DATE_TABLE DATE_FROM
  ON EXTRACT(DAY FROM RECOMMENDATION_ORIGIN_VIDEO_UPLOAD_DATE) = DATE_FROM.day_component_date AND
      EXTRACT(YEAR FROM RECOMMENDATION_ORIGIN_VIDEO_UPLOAD_DATE) = DATE_FROM.year_component_date AND
      EXTRACT(MONTH FROM RECOMMENDATION_ORIGIN_VIDEO_UPLOAD_DATE) = DATE_FROM.month_component_date

JOIN DATE_TABLE DATE_TO
  ON EXTRACT(DAY FROM RECOMMENDATION_DESTINATION_VIDEO_UPLOAD_DATE) = DATE_TO.day_component_date AND
      EXTRACT(YEAR FROM RECOMMENDATION_DESTINATION_VIDEO_UPLOAD_DATE) = DATE_TO.year_component_date AND
      EXTRACT(MONTH FROM RECOMMENDATION_DESTINATION_VIDEO_UPLOAD_DATE) = DATE_TO.month_component_date

